require('proof')(16, okay => {
    const Permeate = require('..')

    okay(Permeate('1', '1'), 'strings')
    okay(!Permeate(1, '1'), 'strings fail')
    okay(Permeate(1, 1), 'numbers')
    okay(Permeate({}, {}), 'empty objects')
    okay(Permeate({ code: 'ENOENT' }, {}), 'empty object as subset')
    okay(!Permeate({}, { code: 'ENOENT' }), 'object subset miss')
    okay(Permeate({ code: 'ENOENT' }, { code: /ENOENT/ }), 'nested regex hit')
    okay(!Permeate({ code: 'EBADFD' }, { code: /ENOENT/ }), 'nested regex hit')
    okay(Permeate([ 1, 2, 3 ], [ 1, 2, 3 ]), 'array equal')
    okay(Permeate([ 1, 2, 3 ], [ 1, 2, 3 ], { length: 3 }), 'array equal')
    okay(!Permeate([ 1, 2 ], [ 1, 2, 3 ]), 'array does not contain')
    okay(Permeate([ 1, 2, 2, 3 ], [ 1, 2, 3 ]), 'array contains subset')
    okay(Permeate(/a/, /a/), 'compare regex')
    okay(Permeate(NaN, NaN), 'compare NaN')
    okay(Permeate(new Date(0), new Date(0)), 'compare Date')
    okay(Permeate(null, () => true), 'run function')
})
